name: build
on: [push, pull_request]

jobs:
    test:
        name: Dub Tests
        strategy:
            matrix:
                os: [ubuntu-latest]
                dc: [ldc-latest, ldc-1.20.0, ldc-1.19.0, ldc-1.18.0, ldc-1.17.0, ldc-1.16.0]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v1

            - name: Install D compiler
              uses: mihails-strasuns/setup-dlang@v0.4.0
              with:
                  compiler: ${{ matrix.dc }}

            - name: Run tests
              run: make test
              
            - name: Build
              run: make build
